version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-db
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_ROOT_PASSWORD: xyf123456
      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped